export const DICT = {
  zh: {
    title: "AI 智能秘书",
    subtitle: "你的 HR 与 IT 专属副驾",
    greeting: { employee: "今天能帮到你什么？", manager: "团队管理助手就绪", admin: "系统管理模式，随时待命" },
    greetingSub: { employee: "试着问问关于年假余额、重置密码或者查询最近的报销进度。", manager: "可以查看团队考勤、审批申请、了解团队动态。", admin: "可直接查询和修改员工数据，查看全公司统计。" },
    suggestions: {
      employee: ["我的年假还剩多少天？", "我的电脑连不上 VPN 怎么办？", "帮我解释一下这个月的工资扣款明细", "如何申请新的设计软件授权？"],
      manager: ["查看团队本月考勤概览", "查看待我审批的申请", "团队本月出勤率怎么样", "最近谁请假了"],
      admin: ["查询员工 张伟 的信息", "全公司目前在职多少人", "本月全公司考勤异常统计", "修改员工 刘洋 的部门为产品部"],
    },
    suggestionIcons: { employee: ['🏖️','💻','💰','🔑'], manager: ['📊','📋','📈','🏖️'], admin: ['🔍','👥','📊','✏️'] },
    placeholder: "有什么问题随时问我...",
    poweredBy: "基于火山引擎豆包大模型提供支持",
    clear: "清空对话",
    profile: "个人中心",
    admin: "管理后台",
    dashboard: "数据看板",
    knowledge: "知识库",
    logout: "退出登录",
    feedback: "已反馈",
    helpful: "有帮助",
    dissatisfied: "不满意",
    confirmSubmit: "确认提交",
    modify: "修改信息",
  },
  en: {
    title: "AI Secretary",
    subtitle: "Your HR & IT Copilot",
    greeting: { employee: "How can I help you today?", manager: "Team management assistant ready", admin: "Admin mode, ready to serve" },
    greetingSub: { employee: "Try asking about your remaining leave balance, resetting your password, or tracking a recent expense.", manager: "Check team attendance, review approvals, or see team updates.", admin: "Search and update employee data, view company-wide stats." },
    suggestions: {
      employee: ["What is my remaining leave balance?", "My laptop won't connect to the VPN", "Explain my payroll deductions this month", "How do I request a new software license?"],
      manager: ["Show team attendance this month", "View pending approvals", "Team attendance rate this month", "Who is on leave recently"],
      admin: ["Search employee Zhang Wei", "How many active employees total", "Company-wide attendance anomalies", "Change employee Liu Yang's department"],
    },
    suggestionIcons: { employee: ['🏖️','💻','💰','🔑'], manager: ['📊','📋','📈','🏖️'], admin: ['🔍','👥','📊','✏️'] },
    placeholder: "Ask the secretary anything...",
    poweredBy: "Powered by Volcengine Doubao",
    clear: "Clear chat",
    profile: "Profile",
    admin: "Admin",
    dashboard: "Dashboard",
    knowledge: "Knowledge",
    logout: "Logout",
    feedback: "Sent",
    helpful: "Helpful",
    dissatisfied: "Not satisfied",
    confirmSubmit: "Confirm & Submit",
    modify: "Edit Info",
  }
};

export const SHORTCUTS_ALL = {
  employee: [
    { emoji: '🏖️', text: '我想请假', shortLabel: '请假', bg: 'rgba(94,106,210,0.15)', border: 'rgba(94,106,210,0.3)', color: '#5e6ad2' },
    { emoji: '📊', text: '查一下我的年假余额', shortLabel: '年假余额', bg: 'rgba(16,185,129,0.12)', border: 'rgba(16,185,129,0.25)', color: '#10b981' },
    { emoji: '📋', text: '查看我的申请记录', shortLabel: '申请记录', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.25)', color: '#f59e0b' },
    { emoji: '⏰', text: '查一下我的考勤记录', shortLabel: '考勤', bg: 'rgba(99,102,241,0.12)', border: 'rgba(99,102,241,0.25)', color: '#6366f1' },
    { emoji: '💰', text: '查一下我的薪资明细', shortLabel: '薪资明细', bg: 'rgba(244,63,94,0.12)', border: 'rgba(244,63,94,0.25)', color: '#f43f5e' },
    { emoji: '🔑', text: '帮我重置密码', shortLabel: '重置密码', bg: 'rgba(139,92,246,0.12)', border: 'rgba(139,92,246,0.25)', color: '#8b5cf6' },
    { emoji: '💻', text: 'VPN连不上怎么办', shortLabel: 'VPN排障', bg: 'rgba(6,182,212,0.12)', border: 'rgba(6,182,212,0.25)', color: '#06b6d4' },
    { emoji: '📝', text: '帮我起草一封邮件', shortLabel: '起草邮件', bg: 'rgba(249,115,22,0.12)', border: 'rgba(249,115,22,0.25)', color: '#f97316' },
  ],
  manager: [
    { emoji: '📊', text: '查看团队本月考勤概览', shortLabel: '团队考勤', bg: 'rgba(99,102,241,0.12)', border: 'rgba(99,102,241,0.25)', color: '#6366f1' },
    { emoji: '📋', text: '查看待我审批的申请', shortLabel: '待审批', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.25)', color: '#f59e0b' },
    { emoji: '📈', text: '团队本月出勤率怎么样', shortLabel: '出勤率', bg: 'rgba(16,185,129,0.12)', border: 'rgba(16,185,129,0.25)', color: '#10b981' },
    { emoji: '🏖️', text: '最近谁请假了', shortLabel: '谁请假了', bg: 'rgba(94,106,210,0.12)', border: 'rgba(94,106,210,0.25)', color: '#5e6ad2' },
    { emoji: '👥', text: '查看我的团队成员', shortLabel: '团队成员', bg: 'rgba(139,92,246,0.12)', border: 'rgba(139,92,246,0.25)', color: '#8b5cf6' },
    { emoji: '💰', text: '查一下我的薪资明细', shortLabel: '我的薪资', bg: 'rgba(244,63,94,0.12)', border: 'rgba(244,63,94,0.25)', color: '#f43f5e' },
  ],
  admin: [
    { emoji: '🔍', text: '查询员工信息', shortLabel: '查员工', bg: 'rgba(94,106,210,0.15)', border: 'rgba(94,106,210,0.3)', color: '#5e6ad2' },
    { emoji: '👥', text: '全公司目前在职多少人', shortLabel: '在职统计', bg: 'rgba(16,185,129,0.12)', border: 'rgba(16,185,129,0.25)', color: '#10b981' },
    { emoji: '📊', text: '本月全公司考勤异常统计', shortLabel: '异常考勤', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.25)', color: '#f59e0b' },
    { emoji: '✏️', text: '修改员工信息', shortLabel: '改信息', bg: 'rgba(139,92,246,0.12)', border: 'rgba(139,92,246,0.25)', color: '#8b5cf6' },
    { emoji: '💰', text: '查看全公司统计数据', shortLabel: '公司统计', bg: 'rgba(244,63,94,0.12)', border: 'rgba(244,63,94,0.25)', color: '#f43f5e' },
    { emoji: '📋', text: '查看待审批的申请', shortLabel: '待审批', bg: 'rgba(99,102,241,0.12)', border: 'rgba(99,102,241,0.25)', color: '#6366f1' },
  ],
};
